// <auto-generated />
using System;
using AuthService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20251102133106_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Catalog.Create"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Catalog.Update"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Catalog.Delete"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Orders.Create"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Orders.ReadAll"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Orders.ReadOwn"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Orders.CancelOwn"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Orders.UpdateStatusAll"
                        },
                        new
                        {
                            Id = 9,
                            Name = "OrderProcessing.Read"
                        },
                        new
                        {
                            Id = 10,
                            Name = "OrderProcessing.BeginAssembly"
                        },
                        new
                        {
                            Id = 11,
                            Name = "OrderProcessing.BeginDelivery"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Users.Create"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Users.ReadAll"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Users.ReadOwn"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Users.UpdateAll"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Users.UpdateOwn"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Users.Block"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Users.Unblock"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Users.AssignRoles"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Users.UnassignRoles"
                        });
                });

            modelBuilder.Entity("AuthService.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("AuthService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@system.com",
                            HashedPassword = "$2a$11$fixedhashvalueforadmin123000000000",
                            IsActive = true,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("PermissionsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionsId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionsId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionsId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionsId = 6,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionsId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionsId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            PermissionsId = 16,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RolePermissions", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRoles", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
