#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS catalogdb;
    CREATE DATABASE IF NOT EXISTS orderdb;
    CREATE DATABASE IF NOT EXISTS opsdb;
    CREATE DATABASE IF NOT EXISTS onsdb;
    
    GRANT ALL PRIVILEGES ON DATABASE catalogdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE orderdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE opsdb TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE onsdb TO "$POSTGRES_USER";

EOSQL