// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderNotificationService.Infrastructure;

#nullable disable

namespace OrderNotificationService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderNotificationDbContext))]
    partial class OrderNotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderNotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Создан",
                            TemplateText = "Ваш заказ {OrderId} создан."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отменен",
                            TemplateText = "Ваш заказ {OrderId} отменен."
                        },
                        new
                        {
                            Id = 3,
                            Name = "В обработке",
                            TemplateText = "Ваш заказ {OrderId} находится в обработке."
                        },
                        new
                        {
                            Id = 4,
                            Name = "Готов к доставке",
                            TemplateText = "Обработка вашего заказа {OrderId} завершена. Заказ готов к доставке."
                        },
                        new
                        {
                            Id = 5,
                            Name = "В доставке",
                            TemplateText = "Ваш заказ {OrderId} находится в процессе доставки."
                        },
                        new
                        {
                            Id = 6,
                            Name = "Доставлен",
                            TemplateText = "Ваш заказ {OrderId} доставлен по указанному адресу."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
